### PR TITLE
Copies placeholder.png to the imgs folder and added condition to render placholder if image not included in payload. Also added destructuring in a few places.

### LINKED ISSUE #1: #INC-5312: Missing image
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by InevitableWeb**

### CODE REVIEW

**Comment by ghost** [comment]
Thanks InevitableAnup, I'll review the changes right away!

**Review by ghost — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by InevitableAnup** [comment]
How do I fix this? I am unable to to push my code to branch  1-inc-5312-missing-image getting the following error > git remote rename upstream upstream
error: remote upstream already exists.

**Review by ghost — APPROVED** [review]
Excellent job InevitableAnup! You're now able to merge the PR.

**Pull request merged**
